services:
  - type: web
    name: my-pivot-app
    plan: free
    env: python
    buildCommand: "cd frontend && npm install && VITE_API_BASE=\"\" npm run build && cd ../backend && pip install -r requirements.txt"
    startCommand: "cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: DATABASE_URL
        value: postgresql://my_pivot_db_user:UuLuMzKCcAeOte6nTf2UFmGtNFRyjZyw@dpg-d98jg2vaqgkc73dorjc0-a/my_pivot_db
      - key: PYTHON_VERSION
        value: 3.12.0
